### ISSUE TITLE
Can not set placeholder with CardElement::input_text("description", Some("value"))

### ISSUE THREAD

**Issue by HelloWorld668** [shutton/webex-rust#16]
After I create a CardElement with ```CardElement::input_text("description", Some("value"))``` , i got an object with type ```CardElement``` and can not set placeholder , ```placeholder``` is a field of ```InputText```

**Comment by aknarts** [comment]
This is now published onto crates.io and should be available shortly.. Took the liberty of also bundling in dependencies update with the change just so we stay up to date.
