### ISSUE TITLE
DeviceAuthentication fails with Webex error

### ISSUE THREAD

**Issue by sgrimee** [shutton/webex-rust#23]
When running the `device-authentication` example, I get a url like `https://login-k.webex.com/verify?userCode=6c733a...`. Then I enter this url in a browser, I get the following error from Webex: `We've encountered an error. Try again later.`.

I am able to authenticate to webex as myself using something like the OAuth flow implemented [here](https://github.com/Nabushika/webexterm/blob/master/src/main.rs), but not using this crate's `DeviceAuthenticator`.

@grnmeira is it still working for you? I may not be using it correctly

**Comment by grnmeira** [comment]
@sgrimee, thanks for giving it a shot. I'll have a look and get back to you.

**Comment by grnmeira** [comment]
@sgrimee, I know we talked offline, but I'll leave this here for more people that might be interested.

The device authentication API requires the redirection URIs to be set to all of the three:
- https://oauth-helper-a.wbx2.com/helperservice/v1/actions/device/callback
- https://oauth-helper-r.wbx2.com/helperservice/v1/actions/device/callback
- https://oauth-helper-k.wbx2.com/helperservice/v1/actions/device/callback

Unfortunately, using just a single one of those ore anything different than the three will result in that error. More information on it: https://developer.webex.com/docs/login-with-webex#device-grant-flow

**Comment by sgrimee** [comment]
Thanks for the explanation @grnmeira !
