### ISSUE TITLE
Teams parsing fails when no name present

### ISSUE THREAD

**Issue by sgrimee** [shutton/webex-rust#37]
When retrieving the list of teams, the whole operation fails if at least one of the teams has no `name` field. Yes, this happens ;-)
It would be better to either ignore that team and return the others, or (better IMHO) provide a default name.
I'll look into this

**Comment by aknarts** [comment]
Or just make the name Optional, did not know this is a possibility

**Comment by sgrimee** [comment]
Making it optional will mean a change in API... I expect this is a very rare case...
I think just adding #[serde(default)] to the name field of `Room`, `Org`, and `Team` would cover most cases, no?
